language: python
python:
 - "2.6"
 - "2.7"
install:
 - "pip install . --use-mirrors"
 - "pip install -r requirements.pip"
script: nosetests
before_script:
  - sudo apt-get install virtualbox
  - sudo apt-get install vagrant
  - vagrant up
